# Generated by Django 5.1.4 on 2024-12-18 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bin',
            old_name='description',
            new_name='descripcion',
        ),
    ]
